# Base Image and stage-1
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: use nginx and build from stage-1
FROM nginx:stable-alpine

# Replace our custom config file
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Copy built from stage-1
COPY --from=builder /app/dist /usr/share/nginx/html

# Log to stdout and stderr
RUN mkdir -p /var/log/nginx
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
